files:
  - source: /trashapp_common/src/main/res/values/strings.xml
    translation: /trashapp_common/src/main/res/values-%android_code%/%original_file_name%
  - source: /trashapp_common/src/main/res/values/arrays.xml
    translation: /trashapp_common/src/main/res/values-%android_code%/%original_file_name%
